app:
  appId: "wx26e9d10cf1c7fc60"
  appSecret: "d358cd1aafea40674e42a6a9f9c486bd"
info:
  github: https://github.com/abigail830/time-ticket
  jitpack: https://jitpack.io/#abigail830/time-ticket
swagger:
  enable: true