---
- hosts: centOS7
  remote_user: root
  vars:
    version: v0.0.6
  tasks:
  - name: Download package from jitpack
    get_url:
      url: https://jitpack.io/com/github/abigail830/time-ticket/{{version}}/time-ticket-{{version}}.jar
      dest: /var/www/time-ticket-1/time-ticket-{{version}}.jar
      mode: 0744

  - name: Remove existing softlink
    file:
      state: absent
      path: /var/www/time-ticket-1/time-ticket.jar

  - name: Create new softlink to deploy file
    file:
      src: /var/www/time-ticket-1/time-ticket-{{version}}.jar
      dest: /var/www/time-ticket-1/time-ticket.jar
      state: link
      mode: 0744

  - name: Stop current process
    command: /var/www/time-ticket-1/stop.sh

  - name: Start new process
    command: /var/www/time-ticket-1/start.sh

